<?php 
$inputs_panel = [
    [
        "id" => 1,
        "type" => "number",
        "placeholder" => "Precio",
        "ids" => "precio",
        "names" => "precio",
        "span" => "Precio",
        "errores" => "precio",
    ],
    [
        "id" => 2,
        "type" => "number",
        "placeholder" => "Expensas",
        "ids" => "expensas",
        "names" => "expensas",
        "span" => "Expensas",
        "errores" => "expensas",
    ],
    [
        "id" => 3,
        "type" => "number",
        "placeholder" => "Superficie total",
        "ids" => "superficie_total",
        "names" => "superficie_total",
        "span" => "Superficie Total",
        "errores" => "superficie_total",
    ],
    [
        "id" => 4,
        "type" => "number",
        "placeholder" => "Superficie cubierta",
        "ids" => "superficie_cubierta",
        "names" => "superficie_cubierta",
        "span" => "Sup. Cubierta",
        "errores" => "superficie_cubierta",
    ],
    [
        "id" => 5,
        "type" => "number",
        "placeholder" => "Ambientes",
        "ids" => "ambientes",
        "names" => "ambientes",
        "span" => "Ambientes",
        "errores" => "ambientes",
    ],
    [
        "id" => 6,
        "type" => "number",
        "placeholder" => "Baños",
        "ids" => "baños",
        "names" => "baños",
        "span" => "Baños",
        "errores" => "baños",
    ],
    [
        "id" => 7,
        "type" => "number",
        "placeholder" => "Dormitorios",
        "ids" => "dormitorios",
        "names" => "dormitorios",
        "span" => "Dormitorios",
        "errores" => "dormitorios",
    ],
    [
        "id" => 8,
        "type" => "number",
        "placeholder" => "Cocheras",
        "ids" => "cocheras",
        "names" => "cocheras",
        "span" => "Cocheras",
        "errores" => "cocheras",
    ],
    [
        "id" => 9,
        "type" => "number",
        "placeholder" => "Antiguedad",
        "ids" => "antiguedad",
        "names" => "antiguedad",
        "span" => "Antigüedad",
        "errores" => "antiguedad",
    ],
];

?>